image: docker:stable
services:
  - docker:dind

stages:
  - build
  - trigger

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: registry.gitlab.com/hibou-io/hibou-odoo/suite
  GITLAB_BASE_URL: https://gitlab.com
  ENTERPRISE_PROJECT_ID: 10004796

before_script:
  - RELEASE=$(echo $CI_COMMIT_REF_SLUG | sed "s/^\([[:digit:]][[:digit:]]\)-\([[:digit:]]\)/\1\.\2/g")
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_IMAGE:$RELEASE -f Dockerfile-GitLab .
    - docker push $CONTAINER_IMAGE:$RELEASE

trigger11:
  stage: trigger
  script:
    - docker run byrnedo/alpine-curl curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=11.0 $GITLAB_BASE_URL/api/v4/projects/$ENTERPRISE_PROJECT_ID/trigger/pipeline
  only:
    - 11.0

trigger12:
  stage: trigger
  script:
    - docker run byrnedo/alpine-curl curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=12.0 $GITLAB_BASE_URL/api/v4/projects/$ENTERPRISE_PROJECT_ID/trigger/pipeline
  only:
    - 12.0

